#!/bin/bash

echo "Installing flowR addin..."

Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"

Rscript -e "remotes::install_github('flowr-analysis/rstudio-addin-flowr@v0.1.2')"
